### ISSUE TITLE
%matplotlib widget doesn't work for me in VSCode

### ISSUE THREAD

**Issue by tbenthompson** [brendanjmeade/celeri#62]
I remember you use VSCode for a lot of notebook stuff. Have you gotten "%matplotlib widget" working inside VSCode? 

Totally fine if the answer is "no silly, just use jupyter lab/notebook!"

**Comment by brendanjmeade** [comment]
This is really interesting because it didn't work for me for a while when I first tried in on the new M1.  Then, after the strange spaces and font issue magically resolved itself, it started to work for me.  I just checked and it works fine in: estimating_tde_slip.ipynb.   Honestly, this is a mystery to me.  If there are settings listing that I can share, let me know.

**Comment by tbenthompson** [comment]
Huh! I might look into this sometime. But for now I'll close this.

**Comment by tbenthompson** [comment]
Thanks Brendang!
